### PR TITLE
Update to dacs.json for Orchard Audio PecanPi DAC

### PR DESCRIPTION
**Pull request by orchardaudio**
Adding support for Orchard Audio PecanPi DAC

### CODE REVIEW

**Comment by volumio** [comment]
Hi Leo,
sorry but as per https://developers.volumio.com/I2S%20DACs#how-to-get-an-i2s-dac-supported-by-volumio

`Given the increasing number of I2S DACs on the market, Volumio's policy is to accept Pull Requests only for DACs that require a specific overlay to work, and this overlay is not already stated in the JSON File. This way we reduce to the minimum the I2S DACs list and offer a compelling user experience.

If, for example your DAC requires the "hifiberry-dacplus" overlay to work, we won't merge your request for a new DAC that uses this overlay. On your end, simply suggest your users the appropriate entry to select in Volumio to make your DAC work.`

Unless there is a specific reason or a script that needs to be added, we can't merge it. Let me know if there is an additional reason to merge it.

**Comment by orchardaudio** [comment]
> Hi Leo, sorry but as per https://developers.volumio.com/I2S%20DACs#how-to-get-an-i2s-dac-supported-by-volumio
> 
> `Given the increasing number of I2S DACs on the market, Volumio's policy is to accept Pull Requests only for DACs that require a specific overlay to work, and this overlay is not already stated in the JSON File. This way we reduce to the minimum the I2S DACs list and offer a compelling user experience.
> 
> If, for example your DAC requires the "hifiberry-dacplus" overlay to work, we won't merge your request for a new DAC that uses this overlay. On your end, simply suggest your users the appropriate entry to select in Volumio to make your DAC work.`
> 
> Unless there is a specific reason or a script that needs to be added, we can't merge it. Let me know if there is an additional reason to merge it.

Hi,

I do not understand in this case why Volumio is telling my customer that Orchard Audio PecanPi DAC is not supported and pushing them away.

The PecanPi DAC runs perfectly fine with the RPI-DAC interface and this is what I instruct our customers to use.

Thanks;
Leo

**Comment by timothyjward** [comment]
> I do not understand in this case why Volumio is telling my customers that Orchard Audio PecanPi DAC is not supported and pushing them away.

I think this is the exact opposite of what was said. The point is that this new DAC is already supported by Volumio using an existing setting and no update is needed. There are a *very* large number of DACs out there and adding a new entry for every one of them would result in an unusably long list when configuring Volumio. 

To avoid making life harder for Volumio users the policy is that if the new DAC works as a “clone” of an existing one (same overlay, scripts etc) then no new config entry should be created and the existing entry used. 

In this case the assertion from the maintainers is that the Pecan Pi DAC is indistinguishable (in a config sense) from the R-Pi DAC and so that should be what gets selected by the user. The documentation for the Pecan Pi DAC can point the user to this config entry. 

If it is in fact the case that more/different config is needed for this particular DAC then this PR needs to be updated to reflect those changes and it can then be re-reviewed.

**Comment by orchardaudio** [comment]
> I think this is the exact opposite of what was said. The point is that this new DAC is already supported by Volumio using an existing setting and no update is needed. There are a _very_ large number of DACs out there and adding a new entry for every one of them would result in an unusably long list when configuring Volumio.
> 
> To avoid making life harder for Volumio users the policy is that if the new DAC works as a “clone” of an existing one (same overlay, scripts etc) then no new config entry should be created and the existing entry used.
> 
> In this case the assertion from the maintainers is that the Pecan Pi DAC is indistinguishable (in a config sense) from the R-Pi DAC and so that should be what gets selected by the user. The documentation for the Pecan Pi DAC can point the user to this config entry.
> 
> If it is in fact the case that more/different config is needed for this particular DAC then this PR needs to be updated to reflect those changes and it can then be re-reviewed.

You misunderstood what I said.

Some of my customers have contacted Volumio for support for issues not related to the PecanPi DAC like TIDAL connect not working for example. These customers have been told by Volumio tech support they will not work with them because the DAC is not supported and to contact orchard audio.

This is not the case the DAC is fully supported and uses the RPI-DAC overlay.

How do we avoid such instances going forward?

**Comment by timothyjward** [comment]
> You misunderstood what I said.
> 
> Some of my customers have contacted Volumio for support for issues not related to the PecanPi DAC like TIDAL connect not working for example. These customers have been told by Volumio tech support they will not work with them because the DAC is not supported and to contact orchard audio.
> 
> This is not the case the DAC is fully supported and uses the RPI-DAC overlay.
> 
> How do we avoid such instances going forward?
> 
> I was figuring having the DAC name in the dropdown would solve this problem.

I’m afraid that I can’t really comment about the volumio support organisation (I have worked on the Open Source side). For that you would be best contacting Volumio directly. 

I can say that there is no requirement to have an entry in this list to be a “volumio supported card” and that lots of DACs can be (and are) used as “clones” of existing entries.

**Comment by orchardaudio** [comment]
> I’m afraid that I can’t really comment about the volumio support organization (I have worked on the Open Source side). For that, you would be best contacting Volumio directly.

Do you have contact information for them?

**Comment by orchardaudio** [comment]
As the policy has been changed, can you please also add the PecanPi+ DAC to the list. The PecanPi+ DAC uses the hifiberry DAC PLUS DSP overlay.

**Comment by volumio** [comment]
Please send another PR accordingly

**Pull request closed without merging**
